server:
  port: ${port:8082}
spring:
  profiles:
    active: ${profile} 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 2
          multiplier: 1.5
          max-interval: 5000
    request:
      exchange:
        name: ${exchange}
      queue:
        name: ${queue-name}
        routing-key: ${queue-routing-key}
      dead-letter:
        name: ${deadletter-name}
        routing-key: ${deadletter-routing-key}
      parking-lot:
        name: ${parkinglot-name}
        routing-key: ${parkinglot-routing-key}
